### ISSUE TITLE
i got a 500 server error??

### ISSUE THREAD

**Issue by Daargajedan** [xkonni/snapcastr#7]
[2018-04-19 07:28:40,433] ERROR in app: Exception on /page/base [GET]
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/.local/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/.local/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/pi/.local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/.local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/snapcastr/snapcastr/snapcastr.py", line 64, in basep
    loop, snapserver = start_server()
  File "/home/pi/snapcastr/snapcastr/snapcastr.py", line 45, in start_server
    snapserver = loop.run_until_complete(run_test(loop))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/pi/snapcastr/snapcastr/snapcastr.py", line 40, in run_test
    return (yield from snapcast.control.create_server(loop, server_addr, reconnect=True))
  File "/home/pi/.local/lib/python3.5/site-packages/snapcast/control/__init__.py", line 11, in create_server
    yield from server.start()
  File "/home/pi/.local/lib/python3.5/site-packages/snapcast/control/server.py", line 85, in start
    yield from self._do_connect()
  File "/home/pi/.local/lib/python3.5/site-packages/snapcast/control/server.py", line 95, in _do_connect
    lambda: SnapcastProtocol(self._callbacks), self._host, self._port)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 731, in create_connection
    infos = f1.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
192.168.1.3 - - [19/Apr/2018 07:28:40] "GET /page/base HTTP/1.1" 500 -

**Comment by mariolukas** [comment]
Try to start with `--host=localhost` or `--host=127.0.0.1`

**Comment by xkonni** [comment]
should be easier now with the latest changes.
